 // CADASTRA Cliente
POST http://localhost:3000/custumers
Content-Type: application/json

{
  "name": "alex",
  "email": "alex@email.com",
  "password": "alex"
}
###
GET  http://localhost:3000/custumers
