GET http://localhost:3000/products

###
// LISTANDO PELO SLUG
GET http://localhost:3000/products/cadeira-gamer

###

// LISTANDO PELO ID
GET http://localhost:3000/products/admin/6695a2ab6bb48d6e8c2dfddc

###

// LISTANDO PELA TAG
GET http://localhost:3000/products/tags/informatica

###

 // CADASTRA PRODUTOS
POST http://localhost:3000/products
Content-Type: application/json

{
  "title": "gato gamer",
  "slug": "gato-gamer",
  "description": "gato colorido gamer",
  "price": 19.99,
  "active": true,

  "tags": ["informatica", "gato", "game"]
}



###

PUT  http://localhost:3000/products/668f314122990c0eab90dad7
Content-Type: application/json

{
   "title": "mesa-gamer v2",
        "description": "mesa rgb 19 modos de luz",
    "price": 100,
    "slug": "mesa-gamer"
}
###
DELETE   http://localhost:3000/products/6695a3385aefab987494edf0
Content-Type: application/json

