GET http://localhost:3000/products

###
// LISTANDO PELO SLUG
GET http://localhost:3000/products/fone-gamer

###

// LISTANDO PELO ID
GET http://localhost:3000/products/admin/668f1b640bc5b699927a0ab4

###

// LISTANDO PELA TAG
GET http://localhost:3000/products/tags/informatica

###

 // CADASTRA PRODUTOS
POST http://localhost:3000/products
Content-Type: application/json

{
  "title": "mesa gamer",
  "slug": "mesa-gamer",
  "description": "mesa rgb 13 modos de luz",
  "price": 99.99,
  "active": true,
  "tags": ["informatica", "mesa", "game"]
}

###

PUT  http://localhost:3000/products/668dc8569b150d910b9bdb8c
Content-Type: application/json

{
   "title": "Cadeira-gamer v2",
        "description": "Cadeira desconfortavel",
    "price": 1.299,
    "slug": "Cadeira-gamer"
}
###
DELETE   http://localhost:3000/products/668f1b640bc5b699927a0ab4
Content-Type: application/json

